;///////////////////////////////////////////////////////////////////////
;// Mirrored Playfield Demo - Screen built with TIA Playfield Painter //
;//               by Christian Bogey - April 25 , 2004                //		
;///////////////////////////////////////////////////////////////////////

                processor 6502 
                include "vcs.h" 
                include "macro.h" 

;/////////////////  Start of Code ///////////////////////////////////// 

                SEG 
                ORG $F000 

Reset 
    		; Clear RAM, TIA registers and Set Stack Pointer to #$FF
		SEI
		CLD	
		LDX #$FF
		TXS
		LDA #0
Clear_Mem
		STA 0,X
		DEX
		BNE Clear_Mem			
		
                LDA #$00
                STA COLUBK	; Set Background to Black
                LDA #15*7
                STA COLUPF
                LDA #%00000001  ; Mirrored Playfield
                STA CTRLPF

;///////////////////  Picture Starts Here /////////////////////////////

Start_Frame 

    	; Start VSYNC

                LDA #2 
                STA VSYNC 

                STA WSYNC 
                STA WSYNC 
                STA WSYNC    	; 3 Scanlines of VSYNC 

                LDA #0 
                STA VSYNC	; End VSYNC         


	; 37 Scanlines of Vertical Blank... 
           
       		LDX 37
Vertical_Blank  STA WSYNC 
                DEX 
                BNE Vertical_Blank 
                
                LDA #0 
                STA VBLANK 	; Enable TIA Output
                                
;////////////// Start To Draw Playfield ///////////////////////////////      	
          
		LDX #192	; 192 Scanlines to Display
Draw_Picture		
		LDA Screen_PF0-1,X
		STA PF0
		LDA Screen_PF1-1,X
		STA PF1
		LDA Screen_PF2-1,X
		STA PF2
		STA WSYNC
		DEX
		BNE Draw_Picture
		

;////////////// End Of Display ////////////////////////////////////////      	
    
		LDA #%01000010 		; Disable VIA Output
                STA VBLANK           

	; 30 scanlines of overscan... 

                LDX #30 
Overscan        STA WSYNC 
                DEX 
                BNE Overscan 

		JMP Start_Frame 	; Build Next Frame

; Playfield generated by TIA Playfield Painter
; Mode Used = MIRRORED
; Playfields generated = PF0, PF1, PF2
; Datas lines are reversed
; 192 Line(s) saved = 191 - 0

Screen_PF0
	.byte #%00100000	; Scanline 191
	.byte #%01010000	; Scanline 190
	.byte #%00100000	; Scanline 189
	.byte #%00000000	; Scanline 188
	.byte #%00000000	; Scanline 187
	.byte #%00000000	; Scanline 186
	.byte #%00000000	; Scanline 185
	.byte #%00000000	; Scanline 184
	.byte #%00000000	; Scanline 183
	.byte #%00000000	; Scanline 182
	.byte #%00000000	; Scanline 181
	.byte #%00000000	; Scanline 180
	.byte #%00000000	; Scanline 179
	.byte #%10000000	; Scanline 178
	.byte #%10000000	; Scanline 177
	.byte #%11000000	; Scanline 176
	.byte #%01000000	; Scanline 175
	.byte #%01100000	; Scanline 174
	.byte #%00110000	; Scanline 173
	.byte #%00000000	; Scanline 172
	.byte #%00000000	; Scanline 171
	.byte #%00000000	; Scanline 170
	.byte #%00000000	; Scanline 169
	.byte #%00000000	; Scanline 168
	.byte #%00000000	; Scanline 167
	.byte #%00000000	; Scanline 166
	.byte #%00000000	; Scanline 165
	.byte #%00000000	; Scanline 164
	.byte #%00000000	; Scanline 163
	.byte #%00000000	; Scanline 162
	.byte #%00000000	; Scanline 161
	.byte #%00000000	; Scanline 160
	.byte #%00000000	; Scanline 159
	.byte #%00000000	; Scanline 158
	.byte #%00000000	; Scanline 157
	.byte #%00000000	; Scanline 156
	.byte #%00000000	; Scanline 155
	.byte #%00000000	; Scanline 154
	.byte #%00000000	; Scanline 153
	.byte #%00000000	; Scanline 152
	.byte #%00000000	; Scanline 151
	.byte #%00000000	; Scanline 150
	.byte #%00000000	; Scanline 149
	.byte #%00000000	; Scanline 148
	.byte #%00000000	; Scanline 147
	.byte #%00000000	; Scanline 146
	.byte #%00000000	; Scanline 145
	.byte #%00000000	; Scanline 144
	.byte #%00000000	; Scanline 143
	.byte #%00000000	; Scanline 142
	.byte #%00000000	; Scanline 141
	.byte #%00000000	; Scanline 140
	.byte #%00000000	; Scanline 139
	.byte #%00000000	; Scanline 138
	.byte #%00000000	; Scanline 137
	.byte #%00000000	; Scanline 136
	.byte #%00000000	; Scanline 135
	.byte #%00000000	; Scanline 134
	.byte #%00000000	; Scanline 133
	.byte #%00000000	; Scanline 132
	.byte #%00000000	; Scanline 131
	.byte #%00000000	; Scanline 130
	.byte #%00000000	; Scanline 129
	.byte #%00000000	; Scanline 128
	.byte #%00000000	; Scanline 127
	.byte #%00000000	; Scanline 126
	.byte #%00000000	; Scanline 125
	.byte #%00000000	; Scanline 124
	.byte #%00000000	; Scanline 123
	.byte #%00000000	; Scanline 122
	.byte #%00000000	; Scanline 121
	.byte #%00000000	; Scanline 120
	.byte #%00000000	; Scanline 119
	.byte #%00000000	; Scanline 118
	.byte #%00000000	; Scanline 117
	.byte #%00000000	; Scanline 116
	.byte #%00000000	; Scanline 115
	.byte #%00000000	; Scanline 114
	.byte #%00000000	; Scanline 113
	.byte #%00000000	; Scanline 112
	.byte #%00010000	; Scanline 111
	.byte #%00010000	; Scanline 110
	.byte #%00100000	; Scanline 109
	.byte #%00100000	; Scanline 108
	.byte #%00100000	; Scanline 107
	.byte #%00100000	; Scanline 106
	.byte #%01000000	; Scanline 105
	.byte #%11000000	; Scanline 104
	.byte #%11010000	; Scanline 103
	.byte #%11110000	; Scanline 102
	.byte #%01010000	; Scanline 101
	.byte #%01000000	; Scanline 100
	.byte #%01000000	; Scanline 99
	.byte #%01000000	; Scanline 98
	.byte #%01000000	; Scanline 97
	.byte #%00100000	; Scanline 96
	.byte #%00100000	; Scanline 95
	.byte #%00100000	; Scanline 94
	.byte #%01100000	; Scanline 93
	.byte #%11110000	; Scanline 92
	.byte #%01100000	; Scanline 91
	.byte #%00100000	; Scanline 90
	.byte #%00100000	; Scanline 89
	.byte #%01100000	; Scanline 88
	.byte #%01000000	; Scanline 87
	.byte #%01000000	; Scanline 86
	.byte #%01000000	; Scanline 85
	.byte #%11000000	; Scanline 84
	.byte #%11010000	; Scanline 83
	.byte #%11110000	; Scanline 82
	.byte #%01010000	; Scanline 81
	.byte #%01000000	; Scanline 80
	.byte #%01000000	; Scanline 79
	.byte #%01000000	; Scanline 78
	.byte #%00100000	; Scanline 77
	.byte #%00100000	; Scanline 76
	.byte #%00100000	; Scanline 75
	.byte #%00100000	; Scanline 74
	.byte #%00100000	; Scanline 73
	.byte #%00010000	; Scanline 72
	.byte #%00010000	; Scanline 71
	.byte #%00000000	; Scanline 70
	.byte #%00000000	; Scanline 69
	.byte #%00000000	; Scanline 68
	.byte #%00000000	; Scanline 67
	.byte #%00000000	; Scanline 66
	.byte #%00000000	; Scanline 65
	.byte #%00000000	; Scanline 64
	.byte #%00000000	; Scanline 63
	.byte #%00000000	; Scanline 62
	.byte #%00000000	; Scanline 61
	.byte #%00000000	; Scanline 60
	.byte #%00000000	; Scanline 59
	.byte #%00000000	; Scanline 58
	.byte #%00000000	; Scanline 57
	.byte #%00000000	; Scanline 56
	.byte #%00000000	; Scanline 55
	.byte #%00000000	; Scanline 54
	.byte #%00000000	; Scanline 53
	.byte #%00000000	; Scanline 52
	.byte #%00000000	; Scanline 51
	.byte #%00000000	; Scanline 50
	.byte #%00000000	; Scanline 49
	.byte #%00000000	; Scanline 48
	.byte #%00000000	; Scanline 47
	.byte #%00000000	; Scanline 46
	.byte #%00000000	; Scanline 45
	.byte #%00000000	; Scanline 44
	.byte #%00000000	; Scanline 43
	.byte #%00000000	; Scanline 42
	.byte #%00000000	; Scanline 41
	.byte #%00000000	; Scanline 40
	.byte #%00000000	; Scanline 39
	.byte #%00000000	; Scanline 38
	.byte #%00000000	; Scanline 37
	.byte #%00000000	; Scanline 36
	.byte #%00000000	; Scanline 35
	.byte #%00000000	; Scanline 34
	.byte #%00000000	; Scanline 33
	.byte #%00000000	; Scanline 32
	.byte #%00000000	; Scanline 31
	.byte #%00000000	; Scanline 30
	.byte #%00000000	; Scanline 29
	.byte #%00000000	; Scanline 28
	.byte #%00000000	; Scanline 27
	.byte #%00000000	; Scanline 26
	.byte #%00110000	; Scanline 25
	.byte #%01100000	; Scanline 24
	.byte #%01000000	; Scanline 23
	.byte #%11000000	; Scanline 22
	.byte #%10000000	; Scanline 21
	.byte #%10000000	; Scanline 20
	.byte #%10000000	; Scanline 19
	.byte #%10000000	; Scanline 18
	.byte #%00000000	; Scanline 17
	.byte #%00000000	; Scanline 16
	.byte #%00000000	; Scanline 15
	.byte #%00000000	; Scanline 14
	.byte #%00000000	; Scanline 13
	.byte #%00000000	; Scanline 12
	.byte #%00000000	; Scanline 11
	.byte #%00000000	; Scanline 10
	.byte #%00000000	; Scanline 9
	.byte #%00000000	; Scanline 8
	.byte #%00000000	; Scanline 7
	.byte #%00000000	; Scanline 6
	.byte #%00000000	; Scanline 5
	.byte #%00000000	; Scanline 4
	.byte #%00000000	; Scanline 3
	.byte #%00100000	; Scanline 2
	.byte #%01010000	; Scanline 1
	.byte #%00100000	; Scanline 0

Screen_PF1
	.byte #%00100000	; Scanline 191
	.byte #%00100000	; Scanline 190
	.byte #%00100000	; Scanline 189
	.byte #%00100000	; Scanline 188
	.byte #%00100000	; Scanline 187
	.byte #%01000000	; Scanline 186
	.byte #%01000000	; Scanline 185
	.byte #%01000000	; Scanline 184
	.byte #%01000000	; Scanline 183
	.byte #%01000000	; Scanline 182
	.byte #%10000000	; Scanline 181
	.byte #%10000000	; Scanline 180
	.byte #%10000000	; Scanline 179
	.byte #%00000000	; Scanline 178
	.byte #%00000000	; Scanline 177
	.byte #%00000000	; Scanline 176
	.byte #%00000000	; Scanline 175
	.byte #%00000000	; Scanline 174
	.byte #%00000000	; Scanline 173
	.byte #%00000000	; Scanline 172
	.byte #%00000000	; Scanline 171
	.byte #%00000000	; Scanline 170
	.byte #%00000000	; Scanline 169
	.byte #%00000000	; Scanline 168
	.byte #%00000000	; Scanline 167
	.byte #%00000000	; Scanline 166
	.byte #%00000000	; Scanline 165
	.byte #%00000000	; Scanline 164
	.byte #%00000000	; Scanline 163
	.byte #%00000000	; Scanline 162
	.byte #%00000000	; Scanline 161
	.byte #%00000000	; Scanline 160
	.byte #%00000000	; Scanline 159
	.byte #%00000000	; Scanline 158
	.byte #%00000000	; Scanline 157
	.byte #%00000000	; Scanline 156
	.byte #%00000000	; Scanline 155
	.byte #%00000000	; Scanline 154
	.byte #%00000000	; Scanline 153
	.byte #%00000000	; Scanline 152
	.byte #%00000000	; Scanline 151
	.byte #%00000000	; Scanline 150
	.byte #%00000000	; Scanline 149
	.byte #%00000000	; Scanline 148
	.byte #%00000000	; Scanline 147
	.byte #%00000000	; Scanline 146
	.byte #%00000000	; Scanline 145
	.byte #%00000000	; Scanline 144
	.byte #%00000000	; Scanline 143
	.byte #%00000000	; Scanline 142
	.byte #%00000001	; Scanline 141
	.byte #%00000001	; Scanline 140
	.byte #%00000001	; Scanline 139
	.byte #%00000001	; Scanline 138
	.byte #%00000001	; Scanline 137
	.byte #%00000011	; Scanline 136
	.byte #%00000011	; Scanline 135
	.byte #%00000011	; Scanline 134
	.byte #%00000011	; Scanline 133
	.byte #%00000010	; Scanline 132
	.byte #%00000110	; Scanline 131
	.byte #%00000110	; Scanline 130
	.byte #%00000110	; Scanline 129
	.byte #%00000110	; Scanline 128
	.byte #%00000110	; Scanline 127
	.byte #%00001110	; Scanline 126
	.byte #%00001110	; Scanline 125
	.byte #%00001110	; Scanline 124
	.byte #%00001110	; Scanline 123
	.byte #%00001110	; Scanline 122
	.byte #%00001110	; Scanline 121
	.byte #%00001100	; Scanline 120
	.byte #%00001100	; Scanline 119
	.byte #%00001100	; Scanline 118
	.byte #%00011100	; Scanline 117
	.byte #%00011100	; Scanline 116
	.byte #%00011100	; Scanline 115
	.byte #%00011100	; Scanline 114
	.byte #%00011100	; Scanline 113
	.byte #%00011100	; Scanline 112
	.byte #%00111100	; Scanline 111
	.byte #%00111100	; Scanline 110
	.byte #%00111100	; Scanline 109
	.byte #%00111110	; Scanline 108
	.byte #%00111010	; Scanline 107
	.byte #%00111010	; Scanline 106
	.byte #%00111010	; Scanline 105
	.byte #%01111001	; Scanline 104
	.byte #%11111001	; Scanline 103
	.byte #%01111001	; Scanline 102
	.byte #%00111001	; Scanline 101
	.byte #%00111000	; Scanline 100
	.byte #%00111000	; Scanline 99
	.byte #%00111000	; Scanline 98
	.byte #%00111000	; Scanline 97
	.byte #%00111000	; Scanline 96
	.byte #%00111000	; Scanline 95
	.byte #%00111000	; Scanline 94
	.byte #%10111000	; Scanline 93
	.byte #%11111000	; Scanline 92
	.byte #%10111000	; Scanline 91
	.byte #%00111000	; Scanline 90
	.byte #%00111000	; Scanline 89
	.byte #%00111000	; Scanline 88
	.byte #%00111000	; Scanline 87
	.byte #%00111000	; Scanline 86
	.byte #%00111000	; Scanline 85
	.byte #%01111000	; Scanline 84
	.byte #%11111000	; Scanline 83
	.byte #%01111000	; Scanline 82
	.byte #%00111000	; Scanline 81
	.byte #%00111000	; Scanline 80
	.byte #%00111000	; Scanline 79
	.byte #%00111000	; Scanline 78
	.byte #%00111000	; Scanline 77
	.byte #%00111001	; Scanline 76
	.byte #%00111001	; Scanline 75
	.byte #%00111001	; Scanline 74
	.byte #%00111001	; Scanline 73
	.byte #%00011001	; Scanline 72
	.byte #%00011001	; Scanline 71
	.byte #%00011101	; Scanline 70
	.byte #%00011101	; Scanline 69
	.byte #%00011101	; Scanline 68
	.byte #%00011110	; Scanline 67
	.byte #%00011110	; Scanline 66
	.byte #%00011110	; Scanline 65
	.byte #%00011110	; Scanline 64
	.byte #%00001110	; Scanline 63
	.byte #%00001110	; Scanline 62
	.byte #%00001110	; Scanline 61
	.byte #%00001110	; Scanline 60
	.byte #%00001110	; Scanline 59
	.byte #%00001110	; Scanline 58
	.byte #%00001110	; Scanline 57
	.byte #%00000110	; Scanline 56
	.byte #%00000110	; Scanline 55
	.byte #%00000110	; Scanline 54
	.byte #%00000110	; Scanline 53
	.byte #%00000110	; Scanline 52
	.byte #%00000110	; Scanline 51
	.byte #%00000011	; Scanline 50
	.byte #%00000011	; Scanline 49
	.byte #%00000011	; Scanline 48
	.byte #%00000011	; Scanline 47
	.byte #%00000011	; Scanline 46
	.byte #%00000001	; Scanline 45
	.byte #%00000001	; Scanline 44
	.byte #%00000001	; Scanline 43
	.byte #%00000000	; Scanline 42
	.byte #%00000000	; Scanline 41
	.byte #%00000000	; Scanline 40
	.byte #%00000000	; Scanline 39
	.byte #%00000000	; Scanline 38
	.byte #%00000000	; Scanline 37
	.byte #%00000000	; Scanline 36
	.byte #%00000000	; Scanline 35
	.byte #%00000000	; Scanline 34
	.byte #%00000000	; Scanline 33
	.byte #%00000000	; Scanline 32
	.byte #%00000000	; Scanline 31
	.byte #%00000000	; Scanline 30
	.byte #%00000000	; Scanline 29
	.byte #%00000000	; Scanline 28
	.byte #%00000000	; Scanline 27
	.byte #%00000000	; Scanline 26
	.byte #%00000000	; Scanline 25
	.byte #%00000000	; Scanline 24
	.byte #%00000000	; Scanline 23
	.byte #%00000000	; Scanline 22
	.byte #%00000000	; Scanline 21
	.byte #%00000000	; Scanline 20
	.byte #%00000000	; Scanline 19
	.byte #%10000000	; Scanline 18
	.byte #%10000000	; Scanline 17
	.byte #%10000000	; Scanline 16
	.byte #%10000000	; Scanline 15
	.byte #%10000000	; Scanline 14
	.byte #%10000000	; Scanline 13
	.byte #%11000000	; Scanline 12
	.byte #%01000000	; Scanline 11
	.byte #%01000000	; Scanline 10
	.byte #%01000000	; Scanline 9
	.byte #%01000000	; Scanline 8
	.byte #%01000000	; Scanline 7
	.byte #%00100000	; Scanline 6
	.byte #%00100000	; Scanline 5
	.byte #%00100000	; Scanline 4
	.byte #%00100000	; Scanline 3
	.byte #%00100000	; Scanline 2
	.byte #%00100000	; Scanline 1
	.byte #%00100000	; Scanline 0

Screen_PF2
	.byte #%00000000	; Scanline 191
	.byte #%00000000	; Scanline 190
	.byte #%00000000	; Scanline 189
	.byte #%00000000	; Scanline 188
	.byte #%00000000	; Scanline 187
	.byte #%00000000	; Scanline 186
	.byte #%00000000	; Scanline 185
	.byte #%00000000	; Scanline 184
	.byte #%00000000	; Scanline 183
	.byte #%00000000	; Scanline 182
	.byte #%00000000	; Scanline 181
	.byte #%00000000	; Scanline 180
	.byte #%00000000	; Scanline 179
	.byte #%00000000	; Scanline 178
	.byte #%00000000	; Scanline 177
	.byte #%00000000	; Scanline 176
	.byte #%00000000	; Scanline 175
	.byte #%00000000	; Scanline 174
	.byte #%00000000	; Scanline 173
	.byte #%00000000	; Scanline 172
	.byte #%00000000	; Scanline 171
	.byte #%00000000	; Scanline 170
	.byte #%00000000	; Scanline 169
	.byte #%00000000	; Scanline 168
	.byte #%00000000	; Scanline 167
	.byte #%00000000	; Scanline 166
	.byte #%00000000	; Scanline 165
	.byte #%00000000	; Scanline 164
	.byte #%00000000	; Scanline 163
	.byte #%00000000	; Scanline 162
	.byte #%00000000	; Scanline 161
	.byte #%00000000	; Scanline 160
	.byte #%00000000	; Scanline 159
	.byte #%00000000	; Scanline 158
	.byte #%00000000	; Scanline 157
	.byte #%11100000	; Scanline 156
	.byte #%00110000	; Scanline 155
	.byte #%00011000	; Scanline 154
	.byte #%00001000	; Scanline 153
	.byte #%00000100	; Scanline 152
	.byte #%00000100	; Scanline 151
	.byte #%00000100	; Scanline 150
	.byte #%00000110	; Scanline 149
	.byte #%00001010	; Scanline 148
	.byte #%00011010	; Scanline 147
	.byte #%00010001	; Scanline 146
	.byte #%00110001	; Scanline 145
	.byte #%00100001	; Scanline 144
	.byte #%01100001	; Scanline 143
	.byte #%01000001	; Scanline 142
	.byte #%01000000	; Scanline 141
	.byte #%11000000	; Scanline 140
	.byte #%10000001	; Scanline 139
	.byte #%10000011	; Scanline 138
	.byte #%10000010	; Scanline 137
	.byte #%10000010	; Scanline 136
	.byte #%10000010	; Scanline 135
	.byte #%10000110	; Scanline 134
	.byte #%11000100	; Scanline 133
	.byte #%01000100	; Scanline 132
	.byte #%01000100	; Scanline 131
	.byte #%01001100	; Scanline 130
	.byte #%01001000	; Scanline 129
	.byte #%01101000	; Scanline 128
	.byte #%00101000	; Scanline 127
	.byte #%00011000	; Scanline 126
	.byte #%00010000	; Scanline 125
	.byte #%00010000	; Scanline 124
	.byte #%00010000	; Scanline 123
	.byte #%00010000	; Scanline 122
	.byte #%00010000	; Scanline 121
	.byte #%00010000	; Scanline 120
	.byte #%00100000	; Scanline 119
	.byte #%00100000	; Scanline 118
	.byte #%00100000	; Scanline 117
	.byte #%00100000	; Scanline 116
	.byte #%00100000	; Scanline 115
	.byte #%00100000	; Scanline 114
	.byte #%01000000	; Scanline 113
	.byte #%01000000	; Scanline 112
	.byte #%01000000	; Scanline 111
	.byte #%01000000	; Scanline 110
	.byte #%01000000	; Scanline 109
	.byte #%01000000	; Scanline 108
	.byte #%01000000	; Scanline 107
	.byte #%01000000	; Scanline 106
	.byte #%01000000	; Scanline 105
	.byte #%01000000	; Scanline 104
	.byte #%01000000	; Scanline 103
	.byte #%01000000	; Scanline 102
	.byte #%10000001	; Scanline 101
	.byte #%10000001	; Scanline 100
	.byte #%10000011	; Scanline 99
	.byte #%10000010	; Scanline 98
	.byte #%10000110	; Scanline 97
	.byte #%10000100	; Scanline 96
	.byte #%10001100	; Scanline 95
	.byte #%10001000	; Scanline 94
	.byte #%10011000	; Scanline 93
	.byte #%10010000	; Scanline 92
	.byte #%11110000	; Scanline 91
	.byte #%11000000	; Scanline 90
	.byte #%11110000	; Scanline 89
	.byte #%10011100	; Scanline 88
	.byte #%10000100	; Scanline 87
	.byte #%10000100	; Scanline 86
	.byte #%10000010	; Scanline 85
	.byte #%10000010	; Scanline 84
	.byte #%10000010	; Scanline 83
	.byte #%10000010	; Scanline 82
	.byte #%10000010	; Scanline 81
	.byte #%10000001	; Scanline 80
	.byte #%10000001	; Scanline 79
	.byte #%10000001	; Scanline 78
	.byte #%10000001	; Scanline 77
	.byte #%10000000	; Scanline 76
	.byte #%10000000	; Scanline 75
	.byte #%10000000	; Scanline 74
	.byte #%10000000	; Scanline 73
	.byte #%10000000	; Scanline 72
	.byte #%10000000	; Scanline 71
	.byte #%01000000	; Scanline 70
	.byte #%01000000	; Scanline 69
	.byte #%01000000	; Scanline 68
	.byte #%01000000	; Scanline 67
	.byte #%01000000	; Scanline 66
	.byte #%01000000	; Scanline 65
	.byte #%01000000	; Scanline 64
	.byte #%01000000	; Scanline 63
	.byte #%01000000	; Scanline 62
	.byte #%01000000	; Scanline 61
	.byte #%00100000	; Scanline 60
	.byte #%00100000	; Scanline 59
	.byte #%00100000	; Scanline 58
	.byte #%00100000	; Scanline 57
	.byte #%00100000	; Scanline 56
	.byte #%00100000	; Scanline 55
	.byte #%00110000	; Scanline 54
	.byte #%00110000	; Scanline 53
	.byte #%00110000	; Scanline 52
	.byte #%01110000	; Scanline 51
	.byte #%01010000	; Scanline 50
	.byte #%01001000	; Scanline 49
	.byte #%11001000	; Scanline 48
	.byte #%10001000	; Scanline 47
	.byte #%10001001	; Scanline 46
	.byte #%10000001	; Scanline 45
	.byte #%10000101	; Scanline 44
	.byte #%10000101	; Scanline 43
	.byte #%10000111	; Scanline 42
	.byte #%01000011	; Scanline 41
	.byte #%01100010	; Scanline 40
	.byte #%00100010	; Scanline 39
	.byte #%00100110	; Scanline 38
	.byte #%00100100	; Scanline 37
	.byte #%00100100	; Scanline 36
	.byte #%00110100	; Scanline 35
	.byte #%00011000	; Scanline 34
	.byte #%00011000	; Scanline 33
	.byte #%00110000	; Scanline 32
	.byte #%00100000	; Scanline 31
	.byte #%11000000	; Scanline 30
	.byte #%00000000	; Scanline 29
	.byte #%00000000	; Scanline 28
	.byte #%00000000	; Scanline 27
	.byte #%00000000	; Scanline 26
	.byte #%00000000	; Scanline 25
	.byte #%00000000	; Scanline 24
	.byte #%00000000	; Scanline 23
	.byte #%00000000	; Scanline 22
	.byte #%00000000	; Scanline 21
	.byte #%00000000	; Scanline 20
	.byte #%00000000	; Scanline 19
	.byte #%00000000	; Scanline 18
	.byte #%00000000	; Scanline 17
	.byte #%00000000	; Scanline 16
	.byte #%00000000	; Scanline 15
	.byte #%00000000	; Scanline 14
	.byte #%00000000	; Scanline 13
	.byte #%00000000	; Scanline 12
	.byte #%00000000	; Scanline 11
	.byte #%00000000	; Scanline 10
	.byte #%00000000	; Scanline 9
	.byte #%00000000	; Scanline 8
	.byte #%00000000	; Scanline 7
	.byte #%00000000	; Scanline 6
	.byte #%00000000	; Scanline 5
	.byte #%00000000	; Scanline 4
	.byte #%00000000	; Scanline 3
	.byte #%00000000	; Scanline 2
	.byte #%00000000	; Scanline 1
	.byte #%00000000	; Scanline 0


 	
;////////////// Set Vectors ///////////////////////////////////////////

            ORG $FFFA 

; Interrupt Vectors 

            .word Reset           ; NMI 
            .word Reset           ; RESET 
            .word Reset           ; IRQ 

          END 

